# Generated by Django 3.2.7 on 2021-09-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210925_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('posx', models.FloatField(blank=True, null=True)),
                ('posy', models.FloatField(blank=True, null=True)),
                ('posz', models.FloatField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='verbose_name.product.code')),
                ('name', models.CharField(max_length=200, verbose_name='verbose_name.product.name')),
                ('description', models.CharField(max_length=500, verbose_name='verbose_name.product.description')),
                ('list_price', models.IntegerField(verbose_name='verbose_name.product.list.price')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('properties', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.IntegerField()),
                ('max_qty', models.IntegerField()),
                ('discount_pctg', models.FloatField()),
                ('price', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('incomming', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('price_unit', models.IntegerField()),
                ('price_untaxed', models.IntegerField()),
                ('price_total', models.IntegerField()),
                ('price_tax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_stock_moves', to='stock.location')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_moves', to='stock.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
                ('product_price_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.productpricepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='verbose_name.product.category.code')),
                ('name', models.CharField(max_length=200, verbose_name='verbose_name.product.category.name')),
                ('description', models.CharField(max_length=500, verbose_name='verbose_name.product.category.description')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.productcategory', verbose_name='verbose_name.product.category.parent')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.productcategory', verbose_name='verbose_name.product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('theoretical_qty', models.IntegerField()),
                ('inventory_date', models.DateTimeField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.location'),
        ),
    ]
