# Generated by Django 3.2 on 2021-10-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20211029_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeitem',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.exchange'),
        ),
        migrations.AlterField(
            model_name='exportitem',
            name='export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.export'),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.import'),
        ),
    ]
