# Generated by Django 3.2 on 2021-11-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20211030_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='export_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='import_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
