# Generated by Django 3.2 on 2021-12-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_export_exportitem__export'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquantity',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='ref_inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.inventoryitem'),
        ),
    ]
