# Generated by Django 3.2 on 2021-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_productmove_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='verbose_name.product.code'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='verbose_name.product.category.code'),
        ),
    ]
