# Generated by Django 3.2 on 2021-12-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20211203_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.inventory'),
        ),
    ]
