# Generated by Django 3.2.7 on 2021-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210925_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
