# Generated by Django 3.2.7 on 2021-09-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='verbose_name.codesystem.code')),
                ('name', models.CharField(max_length=200, verbose_name='verbose_name.codesystem.name')),
                ('version', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'codesystem.status.draft'), ('ACTIVE', 'codesystem.status.active'), ('RETIRED', 'codesystem.status.retired')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='verbose_name.model.property.model')),
                ('code', models.CharField(max_length=100, verbose_name='verbose_name.model.property.code')),
                ('name', models.CharField(max_length=200, verbose_name='verbose_name.model.property.name')),
                ('datatype', models.CharField(choices=[('INTEGER', 'codesystem.datatype.int'), ('FOREIGN_KEY', 'codesystem.datatype.foreign.key'), ('MANY_TO_MANY_FIELD', 'codesystem.datatype.manytomany.field'), ('BOOLEAN', 'codesystem.datatype.boolean'), ('FLOAT', 'codesystem.datatype.float'), ('DATE', 'codesystem.datatype.date'), ('DATETIME', 'codesystem.datatype.datetime'), ('STRING', 'codesystem.datatype.string')], max_length=50, verbose_name='verbose_name.model.property.datatype')),
                ('related_model', models.CharField(blank=True, max_length=200, verbose_name='verbose_name.model.property.related.model')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_date',
            new_name='update_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.AddField(
            model_name='user',
            name='display',
            field=models.CharField(blank=True, max_length=100, verbose_name='verbose_name.user.display'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='verbose_name.user.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verbose_name.user.birth_date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'gender.male'), ('FEMALE', 'gender.female'), ('OTHER', 'gender.other'), ('UNKNOWN', 'gender.unknown')], max_length=50, null=True, verbose_name='verbose_name.user.gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='verbose_name.user.is_admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='verbose_name.user.phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profiles', verbose_name='verbose_name.user.profile.picture'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('partner_type', models.CharField(choices=[('CUSTOMER', 'partner.type.customer'), ('COMPANY', 'partner.type.company'), ('AGENT', 'partner.type.agent')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='verbose_name.company.name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='verbose_name.company.phone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='verbose_name.company.address')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], default='DRAFT', max_length=50)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='verbose_name.code.code')),
                ('display', models.CharField(max_length=200, verbose_name='verbose_name.code.display')),
                ('properties', models.JSONField()),
                ('code_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.codesystem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='codesystem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.CreateModel(
            name='AddressBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_blocks', to='core.coding')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_blocks', to='core.coding')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ward_blocks', to='core.coding')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.addressblock', verbose_name='verbose_name.user.address.block'),
        ),
    ]
