# Generated by Django 3.2.7 on 2021-10-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210925_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.company'),
            preserve_default=False,
        ),
    ]
