# Generated by Django 3.2.7 on 2021-09-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Đang chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CANCELED', 'Đã hủy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('PURCHASE', 'Mua hàng'), ('SALE_ORDER', 'Bán hàng'), ('POS_SALE_ORDER', 'Bán lẻ'), ('EXPENSE', 'Chi tiêu'), ('OTHER', 'Khác')], max_length=50),
        ),
    ]
