# Generated by Django 3.2 on 2021-10-23 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20211023_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
