# Generated by Django 3.2 on 2021-10-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20211025_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='ref_class',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ref_pk',
            field=models.BigIntegerField(null=True),
        ),
    ]
