# Generated by Django 3.2 on 2021-10-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20211025_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='cash',
            field=models.BooleanField(default=True),
        ),
    ]
