# Generated by Django 3.2 on 2021-10-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_ledger_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='business_type',
            field=models.CharField(choices=[('PURCHASE', 'business.type.purchase'), ('PURCHASE_RETURN', 'business.type.purchase.return'), ('PURCHASE_DISCOUNT', 'business.type.purchase.discount'), ('SALES', 'business.type.sales'), ('SALES_RETURN', 'business.type.sales.return'), ('SALES_DISCOUNT', 'business.type.sales.discount'), ('POS', 'business.type.pos'), ('POS_RETURN', 'business.type.pos.return'), ('POS_DISCOUNT', 'business.type.pos.discount'), ('EXPENSE', 'business.type.expense'), ('INCOME', 'business.type.income'), ('INTERNAL_TRANSFER', 'business.type.internal.transfer'), ('OTHER', 'business.type.other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='inward',
            field=models.BooleanField(null=True),
        ),
    ]
