# Generated by Django 3.2 on 2021-10-25 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20211025_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='type',
        ),
        migrations.RemoveField(
            model_name='internaltransferitem',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='internaltransferitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='internaltransferitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='internaltransferitem',
            name='update_date',
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
