# Generated by Django 3.2 on 2021-10-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20211025_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeritem',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_credit_accounts', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_debit_accounts', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='ref_class',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='ref_pk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
