# Generated by Django 3.2 on 2021-10-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_pos_locations', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PURCHASE', 'pos.order.type.purchase'), ('DISCOUNT', 'pos.order.type.discount'), ('RETURN', 'pos.order.type.return')], max_length=50)),
                ('date_order', models.DateTimeField()),
                ('note', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'pos.order.status.draft'), ('PENDING', 'pos.order.status.pending'), ('CONFIRMED', 'pos.order.status.confirmed'), ('CANCELED', 'pos.order.status.canceled'), ('RETURNED', 'pos.order.status.returned')], default='DRAFT', max_length=50)),
                ('_export', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_pos_order', to='stock.export')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_pos_orders', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_pos_orders', to='core.partner')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_pos_order', to='accounting.invoice')),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_pos_order', to='accounting.ledger')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_pos_orders', to='pos.location')),
                ('ref_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price_unit', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('expense', models.IntegerField()),
                ('amount_untaxed', models.IntegerField()),
                ('amount_tax', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_pos_order_item', to='accounting.ledgeritem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_pos_order_items', to='stock.product')),
                ('product_price_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_policy_pos_order_items', to='stock.productpricepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField()),
                ('amount_tax', models.IntegerField()),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_pos_order_item_tax', to='accounting.ledgeritem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_pos_order_expense', to='accounting.ledgeritem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_type_pos_order_expenses', to='accounting.expensetype')),
            ],
        ),
    ]
