# Generated by Django 3.2.7 on 2021-09-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210925_1527'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Mô tả')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], default='DRAFT', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], default='DRAFT', max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('base_salary', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], default='DRAFT', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('approve_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'payment.status.draft'), ('PENDING', 'payment.status.pending'), ('APPROVED', 'payment.status.approved'), ('CANCELED', 'payment.status.canceled')], default='DRAFT', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.invoice')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.paymentperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('no_financial_dependents', models.IntegerField()),
                ('leave_days_per_year', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.staff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='employee.staff')),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='employee.staff')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], default='DRAFT', max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_teams', to='employee.staff')),
                ('members', models.ManyToManyField(related_name='member_teams', to='employee.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('NEW', 'task.status.new'), ('IN_PROGRESS', 'task.status.in.progress'), ('DONE', 'task.status.done'), ('CANCELED', 'task.status.canceled')], max_length=50)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.task')),
                ('update_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffWorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('duration', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'workshift.status.draft'), ('PENDING', 'workshift.status.pending'), ('CONFIRMED', 'workshift.status.confirmed'), ('CANCELED', 'workshift.status.canceled')], max_length=50)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.IntegerField(blank=True, null=True)),
                ('hour_salary', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPrepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('approve_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'prepaid.status.draft'), ('PENDING', 'prepaid.status.pending'), ('APPROVED', 'prepaid.status.approved'), ('CANCELED', 'prepaid.status.canceled')], default='DRAFT', max_length=50)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.paymentperiod')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_gross', models.IntegerField()),
                ('amount_bonus', models.IntegerField()),
                ('amount_tax', models.IntegerField()),
                ('amount_prepaid', models.IntegerField()),
                ('amount_net', models.IntegerField()),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.payroll')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeaveDayQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain_qty', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.leavedayperiod')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('qty', models.FloatField()),
                ('paid', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'leave.day.status.draft'), ('PENDING', 'leave.day.status.pending'), ('APPROVED', 'leave.day.status.approved'), ('CANCELED', 'leave.day.status.canceled')], default='DRAFT', max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.checkinmachine')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.staff')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTaxLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('pctg_tax', models.FloatField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.incometaxpolicy')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department'),
        ),
    ]
