# Generated by Django 3.2.7 on 2021-09-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210925_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinmachine',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='incometaxpolicy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leavedayperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Đang chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CANCELED', 'Đã hủy')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffleaveday',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Đang chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CANCELED', 'Đã hủy')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffprepaid',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Đang chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CANCELED', 'Đã hủy')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffworkshift',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Đang chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELED', 'Đã hủy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='status',
            field=models.CharField(choices=[('NEW', 'Chờ thực hiện'), ('IN_PROGRESS', 'Đang thực hiện'), ('DONE', 'Đã hoàn thành'), ('CANCELED', 'Đã hủy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
    ]
