# Generated by Django 3.2.7 on 2021-09-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('core', '0002_auto_20210925_1527'),
        ('accounting', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'purchase.order.status.draft'), ('REQUESTED', 'purchase.order.status.requested'), ('APPROVED', 'purchase.order.status.approved'), ('ORDERED', 'purchase.order.status.ordered'), ('RECEIVED', 'purchase.order.received'), ('CANCELED', 'purchase.order.canceled')], default='DRAFT', max_length=50)),
                ('approve_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approve_purchase_orders', to='employee.staff')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_purchase_orders', to='core.company')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_purchase_order', to='accounting.invoice')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_purchase_orders', to='stock.location')),
                ('order_lines', models.ManyToManyField(related_name='product_move_purchase_orders', to='stock.ProductMove')),
                ('request_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_purchase_orders', to='employee.staff')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.partner')),
            ],
        ),
    ]
