# Generated by Django 3.2.7 on 2021-09-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('REQUESTED', 'Đã yêu cầu'), ('APPROVED', 'Đã duyệt'), ('ORDERED', 'Đã đặt hàng'), ('RECEIVED', 'Đã nhận hàng'), ('CANCELED', 'Đã hủy')], default='DRAFT', max_length=50),
        ),
    ]
