# Generated by Django 3.2.7 on 2021-10-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_product_properties'),
        ('core', '0005_partner_company'),
        ('purchase', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_purchase_orders', to='stock.location', verbose_name='verbose_name.purchase.order.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=500, verbose_name='verbose_name.purchase.order.note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.partner', verbose_name='verbose_name.purchase.order.supplier'),
        ),
    ]
