# Generated by Django 3.2.7 on 2021-10-01 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partner_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_alter_product_properties'),
        ('purchase', '0003_auto_20211001_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approve_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approve_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_purchase_orders', to='stock.location', verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=500, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='request_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.partner', verbose_name='Nhà cung cấp'),
        ),
    ]
