# Generated by Django 3.2.7 on 2021-09-25 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionworkflowstepdeviceuse',
            name='step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionworkflowstep'),
            preserve_default=False,
        ),
    ]
