# Generated by Django 3.2.7 on 2021-09-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_productionworkflowstepdeviceuse_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='devicemaintainance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='devicetemplate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('CONFIRMED', 'Đã xác nhận'), ('PLANNED', 'Đã lên kế hoạch'), ('IN_PROGRESS', 'Đang thực hiện'), ('DONE', 'Đã xong'), ('CANCELED', 'Đã hủy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='status',
            field=models.CharField(choices=[('NEW', 'Chờ thực hiện'), ('IN_PROGRESS', 'Đang thực hiện'), ('PAUSED', 'Đang tạm dừng'), ('DONE', 'Đã xong'), ('CANCELED', 'Đã hủy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productionworkflow',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='working_state',
            field=models.CharField(choices=[('NORMAL', 'Đang hoạt động'), ('BLOCKED', 'Đang ngừng')], max_length=50),
        ),
    ]
