# Generated by Django 3.2 on 2021-11-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('manufacturing', '0002_productbom_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceTemplate',
            new_name='DeviceClass',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='template',
            new_name='_class',
        ),
    ]
