# Generated by Django 3.2 on 2021-11-01 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20211030_1636'),
        ('manufacturing', '0003_auto_20211101_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprocess',
            name='planned_start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 49, 49, 688652)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='stock.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='product_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
