# Generated by Django 3.2 on 2021-11-01 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_devicecategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
