# Generated by Django 3.2 on 2021-11-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_auto_20211101_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='deviceclass',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicemaintainance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('CONFIRMED', 'Đã xác nhận'), ('PLANNED', 'Đã lên kế hoạch'), ('IN_PROGRESS', 'Đang thực hiện'), ('DONE', 'Đã xong'), ('CANCELED', 'Đã hủy')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='status',
            field=models.CharField(choices=[('NEW', 'Chờ thực hiện'), ('IN_PROGRESS', 'Đang thực hiện'), ('PAUSED', 'Đang tạm dừng'), ('DONE', 'Đã xong'), ('CANCELED', 'Đã hủy')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='productionworkflow',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='DRAFT', max_length=50),
        ),
    ]
