# Generated by Django 3.2 on 2021-11-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_auto_20211101_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcenter',
            name='working_state',
            field=models.CharField(choices=[('NORMAL', 'Đang hoạt động'), ('BLOCKED', 'Đang ngừng')], default='NORMAL', max_length=50),
        ),
    ]
