# Generated by Django 3.2 on 2021-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_alter_workcenter_working_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hours_since_last_maintainance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
