# Generated by Django 3.2 on 2021-11-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_auto_20211101_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productbomitem',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='manufacturing.productbom'),
        ),
    ]
