# Generated by Django 3.2 on 2021-11-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_alter_productbomitem_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionworkflow',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='productionworkflow',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productionworkflowstep',
            name='process',
        ),
        migrations.AddField(
            model_name='productionworkflowstep',
            name='workflow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='manufacturing.productionworkflow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionworkflowstepdeviceuse',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_uses', to='manufacturing.productionworkflowstep'),
        ),
    ]
