# Generated by Django 3.2 on 2021-11-02 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211102_1023'),
        ('employee', '0004_auto_20211026_1727'),
        ('manufacturing', '0013_auto_20211102_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionworkflowstepdeviceuse',
            old_name='device',
            new_name='device_class',
        ),
        migrations.RemoveField(
            model_name='productionstep',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='productionstep',
            name='effective_duration',
        ),
        migrations.RemoveField(
            model_name='productionworkflowstep',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='productionworkflowstepdeviceuse',
            name='duration',
        ),
        migrations.AddField(
            model_name='productionstep',
            name='planned_start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 10, 23, 23, 393147)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionworkflowstepdeviceuse',
            name='hour_offset',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionworkflowstepdeviceuse',
            name='hour_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionworkflow'),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductionWorkflowStepEmployeeUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('hour_per_unit', models.IntegerField(blank=True, null=True)),
                ('hour_offset', models.FloatField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='manufacturing.productionworkflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStepEmployeeUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='manufacturing.productionstep')),
                ('workflow_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
            ],
        ),
    ]
