# Generated by Django 3.2 on 2021-11-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0014_auto_20211102_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionprocess',
            name='product',
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='bom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productbom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='planned_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='planned_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='manufacturing.productionprocess'),
        ),
    ]
