# Generated by Django 3.2 on 2021-11-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20211026_1727'),
        ('manufacturing', '0016_auto_20211107_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstepdeviceuse',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.device'),
        ),
        migrations.AlterField(
            model_name='productionstepemployeeuse',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
    ]
