# Generated by Django 3.2 on 2021-10-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SALE', 'sales.order.type.sale'), ('DISCOUNT', 'sales.order.type.discount'), ('RETURN', 'sales.order.type.return')], max_length=50)),
                ('discount', models.IntegerField()),
                ('expense', models.IntegerField()),
                ('amount_untaxed', models.IntegerField()),
                ('amount_tax', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date_order', models.DateTimeField()),
                ('note', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Đang chờ xác nhận'), ('READY_FOR_DELIVERY', 'Chuẩn bị giao hàng'), ('SHIPPED', 'Đã giao hàng'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELED', 'Đã hủy'), ('RETURNED', 'sales.order.status.returned')], default='DRAFT', max_length=50)),
                ('_export', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_sa_order', to='stock.export')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_sa_orders', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_sa_orders', to='core.partner')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sa_order', to='accounting.invoice')),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_sa_order', to='accounting.ledger')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_sa_orders', to='stock.location')),
                ('ref_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price_unit', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('expense', models.IntegerField()),
                ('amount_untaxed', models.IntegerField()),
                ('amount_tax', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_sa_order_item', to='accounting.ledgeritem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sa_order_items', to='stock.product')),
                ('product_price_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_policy_sa_order_items', to='stock.productpricepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField()),
                ('amount_tax', models.IntegerField()),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_sa_order_item_tax', to='accounting.ledgeritem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_sa_order_expense', to='accounting.ledgeritem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_type_sa_order_expenses', to='accounting.expensetype')),
            ],
        ),
    ]
