# Generated by Django 3.2 on 2021-11-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20211123_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexpense',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='orderexpense',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sales.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order'),
        ),
    ]
