# Generated by Django 3.2 on 2021-11-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20211129_2215'),
        ('sales', '0006_auto_20211123_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_move_sa_order_item', to='stock.productmove'),
        ),
    ]
