# Generated by Django 3.2.7 on 2021-09-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('core', '0002_auto_20210925_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('hours_since_last_maintainance', models.FloatField()),
                ('total_hours', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('hours_to_be_maintained', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.devicecategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('planned_end_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'production.status.draft'), ('CONFIRMED', 'production.status.confirmed'), ('PLANNED', 'production.status.planned'), ('IN_PROGRESS', 'production.status.in.progress'), ('DONE', 'production.status.done'), ('CANCELED', 'production.status.canceled')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productbom')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('working_state', models.CharField(choices=[('NORMAL', 'workcenter.state.normal'), ('BLOCKED', 'workcenter.state.blocked')], max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionWorkflowStepDeviceUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.devicetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('sequence', models.IntegerField()),
                ('prior_steps', models.ManyToManyField(to='manufacturing.ProductionWorkflowStep')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionworkflow')),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.workcenter')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('planned_end_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('effective_duration', models.FloatField()),
                ('status', models.CharField(choices=[('NEW', 'production.step.status.new'), ('IN_PROGRESS', 'production.step.status.in.progress'), ('PAUSED', 'production.step.status.paused'), ('DONE', 'production.step.status.done'), ('CANCELED', 'production.step.status.canceled')], max_length=50)),
                ('devices', models.ManyToManyField(to='manufacturing.Device')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionprocess')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionworkflowstep')),
            ],
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionworkflow'),
        ),
        migrations.CreateModel(
            name='ProductBomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productbom')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMaintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.devicetemplate'),
        ),
        migrations.AddField(
            model_name='device',
            name='workcenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.workcenter'),
        ),
    ]
