# Generated by Django 3.2 on 2021-10-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_days_per_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='no_financial_dependents',
            field=models.IntegerField(default=0),
        ),
    ]
