# Generated by Django 3.2 on 2021-10-22 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PURCHASE', 'purchase.order.type.purchase'), ('DISCOUNT', 'purchase.order.type.discount'), ('RETURN', 'purchase.order.type.return')], max_length=50)),
                ('discount', models.IntegerField()),
                ('expense', models.IntegerField()),
                ('amount_untaxed', models.IntegerField()),
                ('amount_tax', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date_order', models.DateTimeField()),
                ('note', models.CharField(max_length=500)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('REQUESTED', 'Đã yêu cầu'), ('APPROVED', 'Đã duyệt'), ('ORDERED', 'Đã đặt hàng'), ('RECEIVED', 'Đã nhận hàng'), ('CANCELED', 'Đã hủy'), ('RETURNED', 'purchase.order.returned')], default='DRAFT', max_length=50)),
                ('_import', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_pu_order', to='stock.import')),
                ('approve_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approve_pu_orders', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_pu_orders', to='core.company')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_pu_order', to='accounting.invoice')),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_pu_order', to='accounting.ledger')),
                ('ref_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.order')),
                ('request_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_pu_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_pu_orders', to='core.partner')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price_unit', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('expense', models.IntegerField()),
                ('amount_untaxed', models.IntegerField()),
                ('amount_tax', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_pu_order_item', to='accounting.ledgeritem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_pu_order_items', to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField()),
                ('amount_tax', models.IntegerField()),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_pu_order_item_tax', to='accounting.ledgeritem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_pu_order_expense', to='accounting.ledgeritem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_type_pu_order_expenses', to='accounting.expensetype')),
            ],
        ),
    ]
