# Generated by Django 3.2 on 2021-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20211123_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexpense',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
