from django.contrib import admin
from .models import *

admin.site.register(Department)
admin.site.register(Employee)
admin.site.register(Team)
admin.site.register(Task)
admin.site.register(TaskUpdate)
admin.site.register(CheckInMachine)
admin.site.register(EmployeeCheckIn)
admin.site.register(LeaveDayPeriod)
admin.site.register(EmployeeLeaveDay)
admin.site.register(IncomeTaxPolicy)
admin.site.register(IncomeTaxLevel)
admin.site.register(EmployeeSalary)
admin.site.register(EmployeeWorkShift)
admin.site.register(PaymentPeriod)
admin.site.register(EmployeePrepaid)
admin.site.register(Payroll)
admin.site.register(EmployeePayment)