# Generated by Django 3.2.7 on 2021-09-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('core', '0002_auto_20210925_1527'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField()),
                ('note', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'sales.order.status.draft'), ('PENDING', 'sales.order.status.pending'), ('CONFIRMED', 'sales.order.status.confirmed'), ('CANCELED', 'sales.order.status.canceled'), ('REFUNDED', 'sales.order.status.refunded')], default='DRAFT', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_pos_orders', to='core.company')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_pos_order', to='accounting.invoice')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_pos_orders', to='stock.location')),
                ('order_lines', models.ManyToManyField(related_name='product_move_pos_orders', to='stock.ProductMove')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_pos_orders', to='core.partner')),
            ],
        ),
    ]
