# Generated by Django 3.2 on 2021-10-11 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211011_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
