# Generated by Django 3.2 on 2021-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_partner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='is_agent',
            new_name='is_organization',
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
