# Generated by Django 3.2.7 on 2021-09-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210925_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swift_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('PURCHASE', 'invoice.type.purchase'), ('SALE_ORDER', 'invoice.type.sale.order'), ('POS_SALE_ORDER', 'invoice.type.pos.sale.order'), ('EXPENSE', 'invoice.type.expense'), ('OTHER', 'invoice.type.other')], max_length=50)),
                ('incoming', models.BooleanField()),
                ('note', models.CharField(max_length=500)),
                ('amount_untaxed', models.IntegerField()),
                ('amount_tax', models.IntegerField()),
                ('amount_total', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='verbose_name.category.code')),
                ('name', models.CharField(max_length=200, verbose_name='verbose_name.category.name')),
                ('description', models.CharField(max_length=500, verbose_name='verbose_name.category.description')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'status.draft'), ('ACTIVE', 'status.active'), ('INACTIVE', 'status.inactive')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=500)),
                ('request_date', models.DateTimeField(null=True)),
                ('approve_date', models.DateTimeField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'expense.status.draft'), ('PENDING', 'expense.status.pending'), ('APPROVED', 'expense.status.approved'), ('CANCELED', 'expense.status.canceled')], max_length=50)),
                ('approve_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approve_expenses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.expensetype')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.invoice')),
                ('request_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
