# Generated by Django 3.2.7 on 2021-09-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Đang chờ xác nhận'), ('READY_FOR_DELIVERY', 'Chuẩn bị giao hàng'), ('SHIPPED', 'Đã giao hàng'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELED', 'Đã hủy'), ('REFUNDED', 'Trả lại')], default='DRAFT', max_length=50),
        ),
    ]
